name: GhostBuster
main: io.github.rypofalem.ghostbuster.GhostBusterPlugin
version: 1.0
api-version: 1.13
website: https://github.com/RypoFalem
author: RypoFalem
description: Prevents a common cause of "ghost blocks"
commands:
  gbtest:
    description:
    usage: "This command is for testing purposes only!\n\n
    /<command> - Give yourself haste 2, nightvision and an unbreakable efficiency 5 diamond pickaxe\n\n
    /<command> toggle - Toggle ghost block protection active/disabled for all players"
    default: OP